name: Deploy Static Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Static Pages
        run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<html><head><title>Pages</title></head><body>' >> index.html
          for file in $(ls *.html | grep -v 'index.html'); do
            echo "<p><a href=\"$file\">$file</a></p>" >> index.html
          done
          echo '</body></html>' >> index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
